### PR TITLE
Use '__self__' instead of 'im_self' everywhere.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Also in `ExtensionClass.h`.

This is part of the too large`plonezope4` branch.

### CODE REVIEW

**Comment by stephan-hof** [comment]
I have just seen 'ExtensionClass.h' on my github Dashboard so I took a look at this commit https://github.com/zopefoundation/AccessControl/pull/26/commits/04f99a939067470928941578b6b2d87e2392d5ab (and only this commit)

Please change it back there to `im_self`. `PyMethodObject` has no `__self__` in python2 nor in python3

https://github.com/python/cpython/blob/3.6/Include/classobject.h#L17
https://github.com/python/cpython/blob/2.7/Include/classobject.h#L37

Woho the python C-API has a macro/function to get it => No access to the fields needed.
https://docs.python.org/3/c-api/method.html?highlight=pymethod_type#c.PyMethod_GET_SELF

**Comment by hannosch** [comment]
@stephan-hof I've changed it back to `im_self` in 620401be4327812aab11b6aef78d2742b8d55dca.

We should update and fix the canonical file in ExtensionClass itself, than copy/paste the improved version to the other projects. The version in ExtensionClass still uses ``->ob_type`` while this copy is already changed. I don't particular like having these diverging versions.

**Comment by mauritsvanrees** [comment]
Thanks for catching that. I simply saw another `im_self` and changed it, did a rebuild for the `.so` and it still worked in both the `AccessControl` and `Zope2` tests, so I assumed it was fine. Apparently the code path is not used in those tests.

And indeed, having those diverging copies of `ExtensionClass.h` is not really nice.

**Comment by stephan-hof** [comment]
I added a pull request for `ExtensionClass.h` here https://github.com/zopefoundation/ExtensionClass/pull/12

Regarding copy&paste of this file. I think the current build tools give us no other choice than doing that.
Take for example the `greenlet` package. It ships a `greenlet.h` having similar content like ExtensionClass to access the C-code.

If I install this in a virtualenv, pip places the file in the following path `<virtualenv location>/include/site/python2.7/greenlet/greenlet.h`.
So far so good, but when another C-extension needs this header file, this include path is not added.
In the end something like this is called
```
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python2.7 -c test.c -o build/temp.linux-x86_64-2.7/test.o
test.c:1:22: fatal error: greenlet.h: No such file or directory
 #include "greenlet.h"
```

I have no idea what buildout does with header files of an egg.

Linux distributions solve this by moving the header files close the cpython header files.
Look for example here: https://packages.debian.org/jessie/amd64/python-greenlet-dev/filelist
Then it is possible to include them via `#include <greenlet/greenlet.h>`

So for a proper solution we need help from the sandbox.

**Comment by hannosch** [comment]
Thx @stephan-hof!

I agree that the "copy file" approach isn't ideal. It isn't that much of a problem, as these files used to be unmodified for a decade :)

We also used to include these via Subversion externals, but with the move to Git decided not to use Git submodules, as those have their own set of issues.

The only other approach I know of is numpy, which has a helper function `numpy.get_include` (https://github.com/numpy/numpy/blob/master/numpy/lib/utils.py#L22), which than gets used inside setup.py as:
```
import numpy as np

Extension('extension_name',
    include_dirs=[np.get_include()])
```
But that also has issues, as numpy now needs to be fully installed, before a package depending on it can be built. Neither pip nor buildout are particularly good at taking this build dependency into account.

So the copy approach isn't great, but so are none of the alternatives.

**Pull request merged**
