### PR TITLE
Do not import UnrestrictedUser as Super to prevent ImportErrors

### PR DESCRIPTION
**Pull request by pbauer**
The change reverted here caused 23 additional failures in http://jenkins.plone.org/view/PLIPs/job/plip-zope4/27/

### CODE REVIEW

**Comment by pbauer** [comment]
This change caused 23 additional failures in http://jenkins.plone.org/view/PLIPs/job/plip-zope4/27/

**Comment by tseaver** [comment]
@pbauer The `Super` name is a longstanding backward-compatibility alias (it has been there since before `AccessControl` was split out into its own repository).  What kinds of errors was it causing?

**Comment by pbauer** [comment]
I see we had both `from .users import UnrestrictedUser` and `from .users import UnrestrictedUser as Super`. In 0edd8b6c34e8d169a52c7ab0a0dc04bb34014f59 @loechel removed the former. Would it be ok to add it back? Otherweise we'd have to change a lot of imports.

**Comment by icemac** [comment]
@pbauer I'd prefer to change the imports as a way forward.
The whole `User.py` only consists of BBB imports and I was thinking of removing the whole module, see #32.

**Comment by loechel** [comment]
@pbauer and @icemac, as it seems to be an unintended remove of a BBB import I would prefer to add it again.

But I would also recommend to change the Imports in the corresponding packages as BBB links should go away, there is already a deprecation warning.

@pbauer I will help changing the import if you point me to the packages.

**Pull request merged**
