### PR TITLE
Try out Python 3.9 on TravisCI.

### PR DESCRIPTION
**Pull request by icemac**
After the final Python 3.9 release we can declare supporting it.

Tests are green as of Python 3.9a4.

### CODE REVIEW

**Comment by icemac** [comment]
Seems https://github.com/zopefoundation/Persistence/issues/22 has to be fixed first.

**Comment by dataflake** [comment]
zopefoundation/Persistence#22 is fixed and forcing `persistence` to a version >= 4.6.1 will stop the MRO-related issues. The tests continue to fail due to zopefoundation/RestrictedPython#193, though. There's no released RestrictedPython with the fix yet.

**Comment by icemac** [comment]
I suggest to postpone working on Python 3.9 compatibility until its first final release. We have the Zope 5 tests as a canary, so the tests of individual packages can be fixed afterwards.

**Comment by dataflake** [comment]
You could also move them to `allow_failures` and merge this in right now. That way we would have a quick way to look at current failures.

**Comment by icemac** [comment]
I am not sure why TravisCI tests do not run. Did I break the config file? (The online tester for .travis.yml seems to be currently offline so I cannot test it and I do not want to install the Ruby checker on my machine.)

**Comment by dataflake** [comment]
`.travis.yml` was broken, but don't ask me what the issue was. I rebuilt it by copying over the Zope configuration and changing it.

If you go to the package's Travis CI build history page and then click on the little "More Options" hamburger menu you see a link for "Requests". That page is where you can see the incoming requests and it will tell you if the file didn't parse. It doesn't tell you why, though.

**Comment by icemac** [comment]
Maybe it did not in the first place because TravisCI had maintenance that day – which I only read afterwards. Thank you for fixing my PR.

**Comment by icemac** [comment]
Thank you!

**Pull request merged**
