### PR TITLE
Adds support for bcrypt AuthEncoding.

### PR DESCRIPTION
**Pull request by mgrbyte**
@tseaver Hi again!

We've hoping to add this, instead of implementing it [here](https://github.com/collective/dexterity.membrane/pull/15).

Would this be possible? I saw your recent comment in #10 about adding new deps, and wonder if this PR is appropriate/reasonable.

### CODE REVIEW

**Comment by mgrbyte** [comment]
sorry, I've made a bit of a mess with the PEP8 changes here, will clean it up.

**Comment by mauritsvanrees** [comment]
+1 from me.
Note that this adds `bcrypt` as dependency.

We may want to pick bcrypt as default encoding/hash, but that is outside the scope of this pull request.

**Comment by icemac** [comment]
*Caution:* This PR collides with PR #9 where ``AuthEncoding`` was extracted into a separate package, so it can be reused even outside Zope2.

**Comment by icemac** [comment]
@mgrbyte I merged #9 to make progress in reusing AuthEncoding. Could you please create a new PR against [AuthEncoding](https://github.com/zopefoundation/AuthEncoding)?

**Comment by mgrbyte** [comment]
@icemac I'll take a look at doing one this w/end.

**Comment by mgrbyte** [comment]
@icemac Sorry for the long delay getting back to you on this.
I've taken a look at porting this to AuthEncoding, but its not clear to me where the `bcrypt` dependency should be specfied (assuming you were asking for a PR against master on AuthEncoding?)

The PR requires the introduction of a new dependency on a 3rd party lib (bcrypt).
Currently, AuthEncoding has not 3rd party deps, and IIRC, people were reluctant to add a hard dependency (e.g adding bcrypt to `install_requires`) - if this now OK, I'll go ahead and submit a PR, since it's fairly trivial to port what I'd already done.

I'm afraid I don't have little motivation besides tying off loose ends here.
I'm no longer working on Zope related things. 
If I can be of assistance in the way of answering questions concerning the PR,
I'll do my best to re-read the code and provide feedback as best I can.
Sorry!

**Comment by icemac** [comment]
@mgrbyte Thank you for coming back to this PR.

I think `bcrypt` could become an optional dependency using an `extras_require` like it is done in [zc.catalog](https://github.com/zopefoundation/zc.catalog/blob/master/setup.py#L68).
Yes, `AuthEncoding` is the right target for the PR, the HashingScheme implementations where moved there.

**Comment by icemac** [comment]
@mgrbyte Thanks for porting your PR to `AuthEncoding`. Thus closing this PR here.

**Pull request closed without merging**
