### PR TITLE
 In `str.format`, check the security for attributes that are accessed. [2.13]

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This builds on https://github.com/zopefoundation/AccessControl/pull/22.

This replaces https://github.com/zopefoundation/Zope/pull/88.

For all tests to pass, we do need one [fix for runText](https://github.com/zopefoundation/Zope/pull/88/commits/f18cf2059b6e2e4f7c045ea381f9af0423f987ee) from that pull request.

### CODE REVIEW

**Comment by icemac** [comment]
There is no Travis for the 2.13 branch. I added it in #24. Cloud you please rebase after this PR has been merged?

**Comment by mauritsvanrees** [comment]
Thanks for adding Travis support!

I have rebased this.

I have also rebased pull request #22, which is a smaller part of this pull request, for easier evaluation. Maybe that one can be merged first, as the Travis tests just passed there, and the current one has a Travis problem that I will look it.

**Comment by mauritsvanrees** [comment]
I have removed most new tests, because they require Zope2, which would require a `test` extra, and lots of version pins to avoid getting too new packages. I tried and I don't want to go there.

We can put the deleted tests in Zope2 once this is merged. They were originally there in https://github.com/zopefoundation/Zope/pull/88, but `AccessControl` was judged to be a better place.  It now seems a better place for the code, but not for the tests.

**Comment by icemac** [comment]
@mauritsvanrees Maybe the need of removing the tests here is a hint that this fix should go to `RestrictedPython` where it can be tested at a lower level.

**Pull request merged**
