### PR TITLE
Add preliminary support for Python 3.12a7.

### PR DESCRIPTION
**Pull request by icemac**
This hopefully fixes https://github.com/zopefoundation/AccessControl/actions/runs/4713168090/jobs/8358693277

### CODE REVIEW

**Comment by icemac** [comment]
o no, `Directory not empty` is back on macOS.

Even the last successful build https://github.com/zopefoundation/AccessControl/actions/runs/4650409246/jobs/8229390839
had this problem.

**Comment by icemac** [comment]
Maybe a pre-release of zope.proxy would help.

**Comment by icemac** [comment]
`zope.proxy` has the same problem as depends on `zope.security`: https://github.com/zopefoundation/zope.proxy/actions/runs/4524463715/jobs/7968314536
But `zope.security` is fine: https://github.com/zopefoundation/zope.security/actions/runs/4713161605/jobs/8358679615
So a pre-release of `zope.security` might help.

**Comment by dataflake** [comment]
You will see the failure as long as there are no `x86_64` wheels found for the problematic dependencies. As soon as the GHA runner tries to build those wheels it will fail.

IMHO the fix is to change how those problematic packages are built in the first place. Those that try to install other C-based dependencies and then find header files all break. Those that have their own copy of the dependency header files don't break.

**Comment by icemac** [comment]
Updating `zope.security` to a7, breaks the tests over there: https://github.com/zopefoundation/zope.security/pull/97

Now we have a problem, Houston.

**Comment by dataflake** [comment]
That's unrelated to the issue here, though. `zope.security` and/or `zope.proxy` apparently need some massaging to be Python 3.12-compatible.

**Comment by icemac** [comment]
No, `AccessControl` is not part of the problem, it has copies of the needed header files (which should be updated BTW (#140)), so I'll have a look at `zope.proxy`.

**Comment by dataflake** [comment]
`AccessControl` is not the problem and I didn't say it was. `zope.security` has the problem. It tries to install `zope.proxy` to get at the headers.

**Comment by icemac** [comment]
Superseded by #141.

**Pull request closed without merging**
