### PR TITLE
Extract ``.AuthEncoding`` to its own package for reuse.

### PR DESCRIPTION
**Pull request by icemac**
The AuthEncoding module  provides methods and classes which are usable outside Zope 2, so I extracted them into a new package [AuthEncoding](https://github.com/zopefoundation/AuthEncoding) which is BBB imported here.

PR for the 2.13 branch.

### CODE REVIEW

**Comment by tseaver** [comment]
I think we should choose *not* to muck with refactorings like this one in a long-stable release branch (including particularly the requirement to add a new dependency).

**Comment by icemac** [comment]
AccessControl 2.13.13 is still the version currently used in Zope 2.13.23.
But you are right this might be a too big change. What about a new 2.14 branch of AccessControl with this change? (In the project I need this PR for I do not want to upgrade to AccessControl 3.x right now because it requires to update other packages, too.)

**Comment by tseaver** [comment]
@icemac does your project work with `AccessControl 2.13.113`?  If so, why do the firedrill to create a 2.14, just to have it depend on the new `AuthEncoding` which was already present in AC?

**Comment by icemac** [comment]
@tseaver Yes, my project currently works with AccessControl 2. It stores passwords in a relational database encoded by ``AuthEncoding``. In the future the database should be accessed by other Python processes, too. So I want the same code base for the password creation and verification in all processes using the database to prevent incompatibilities.

**Comment by hannosch** [comment]
@icemac I've recently bumped the version of AccessControl master to 4.0 (alpha) targeted at Zope 4. Would you be interested in updating this PR, so it can be merged into that?

I don't see a clean way of doing a backport of this to the 3.x or 2.x feature branches. But at least we could put it in 4.0, so you can rely on it going forward.

**Comment by icemac** [comment]
There seems to be a consensus that this PR should not be merge to the 2.13 branch.

**Pull request closed without merging**
