### PR TITLE
Added setup.py keywords.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
`pyroma` was complaining.
I would have pushed to master directly, but that is not allowed without at least one review.

### CODE REVIEW

**Comment by dataflake** [comment]
Saw the test failures on Python 2.7? This appears to be because `zipp` is pulled in as version 3, but only zipp < 1.2 supports Python 2.7

**Comment by icemac** [comment]
Fixed the problem on `master`. Hopefully this makes the PR green.

**Comment by mauritsvanrees** [comment]
Travis passes, but the information does not get to GitHub.
Let me rebase the branch and force push, see if that helps.

**Comment by icemac** [comment]
Thank you.

Just a hint for repositories which require green CI runs: Do not use `[skip ci]` on the last commit. This confuses GitHub because it expects that the tests for the last commit of a PR are green.

**Comment by mauritsvanrees** [comment]
Ah, that makes sense, I'll try to remember that. I do not add ci skip on a PR commit usually, but this was initially intended to go into master directly.

**Comment by jugmac00** [comment]
This is just my personal opinion...

I do not like commits to master directly, as...
- small errors happens, and it is always better when somebody else has a quick look
- even if you watch a repository, you do not get notice when somebody directly works on master

Also, I would not recommend to force push changes, as afaik this messes up previous reviews.

**Comment by mauritsvanrees** [comment]
> I do not like commits to master directly

Sure. But this was part of a batch update of dozens of package, where I quickly check something and move on to the next. If I have to create dozens of pull requests, then I won't do it and these changes won't happen. (No big deal here of course.)

> Also, I would not recommend to force push changes, as afaik this messes up previous reviews.

That did not happen here. You mean in the [`zope.globalrequest` one](https://github.com/zopefoundation/zope.globalrequest/pull/9)? When you need five commits or more in trying to failing to get Travis to run on 3.4, then it is a mess anyway, no matter what you do.
Well, you can do a squash-and-merge in the GitHub UI.

**Comment by jugmac00** [comment]
Just as a general note... all good :-)

And yes, trying to fix Travis is no fun...

**Pull request merged**
